on:
  push:
    branches:
    - main
    - master
    tags:
    - 'v*'

name: Release policy

jobs:


  release:
    permissions:
      # Required to create GH release
      contents: write
      # Required to push to ghcr.io
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-rust.yml@v1
    with:
      input-wasm: sigstore_policy_test
      oci-target: ghcr.io/kubewarden/policies/sigstore-policy-test
    
    secrets:
      workflow-pat: ${{ secrets.WORKFLOW_PAT }}
    
